version: '3.7'
services:
  fan-steal-fe:
    restart: always
    build: .
    container_name: fan-steal-fe
    ports:
      - 3002:3001
    networks:
      - fan-steal
    env_file:
      - .env
networks:
  fan-steal:
    driver: bridge
