// https://eslint.nuxt.com
// Base config is generated by the @nuxt/eslint module (run `nuxi prepare` if missing)
import prettier from 'eslint-config-prettier/flat'
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt()
  .overrideRules({
    'no-console': 'off',
    'vue/multi-word-component-names': 'off',
    'vue/no-mutating-props': 'off',
    '@typescript-eslint/no-explicit-any': 'warn',
  })
  // Must be last: turns off every rule that conflicts with Prettier
  .append(prettier)
